#!/bin/bash
# GitHub Issue Tracker for Claude Code
# Usage: track_issue.sh "type" "title" "description" ["file:line"]

REPO="hussi9/podcastos"
TYPE="${1:-issue-found}"  # gap, issue-found, fix-applied
TITLE="$2"
DESCRIPTION="$3"
LOCATION="${4:-}"

if [ -z "$TITLE" ]; then
    echo "Usage: track_issue.sh <type> <title> <description> [file:line]"
    exit 1
fi

# Build labels
LABELS="claude-tracked,$TYPE"

# Build body
BODY="## Description
$DESCRIPTION

## Details
- **Type**: $TYPE
- **Tracked by**: Claude Code
- **Session**: $(date '+%Y-%m-%d %H:%M:%S')
"

if [ -n "$LOCATION" ]; then
    BODY="$BODY- **Location**: \`$LOCATION\`
"
fi

BODY="$BODY
---
*Auto-generated by Claude Code issue tracking*"

# Create the issue
gh issue create \
    --repo "$REPO" \
    --title "$TITLE" \
    --body "$BODY" \
    --label "$LABELS" 2>&1

echo "Issue tracked: $TITLE"
